# Generated by Django 4.2.2 on 2023-07-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('text', models.TextField(verbose_name='текст')),
                ('number', models.IntegerField(verbose_name='стоимость(цифры)')),
            ],
            options={
                'verbose_name': 'доска объявлений',
                'verbose_name_plural': 'доски объявлений',
            },
        ),
    ]
